export enum ActionTypes{
    ADD_TO_CART_REQUEST="ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE="ADD_TO_CART_FAILURE",
    GET_DATA_TO_CART_REQUEST="GET_DATA_TO_CART_REQUEST",
    GET_DATA_TO_CART_SUCCESS="GET_DATA_TO_CART_SUCCESS",
    GET_DATA_TO_CART_FAILURE="GET_DATA_TO_CART_FAILURE",
}